import type { PrayerLanguageCode } from "@/lib/prayers/prayer-languages";

/** Optional book-specific blurbs; category blurbs fill gaps. */
const BOOK_BLURBS: Partial<
  Record<string, Partial<Record<PrayerLanguageCode, string>>>
> = {
  "genesis": {
    "en": "God creates the heavens and the earth and begins his covenant with Abraham.",
    "ko": "하나님께서 천지를 창조하시고 아브라함과 언약을 시작하십니다.",
    "es": "Dios crea el cielo y la tierra e inicia su alianza con Abraham.",
    "fr": "Dieu crée les cieux et la terre et commence son alliance avec Abraham.",
    "pt": "Dios crea el cielo y la tierra e inicia su alianza con Abraham.",
    "it": "Dio crea il cielo e la terra e inizia l'alleanza con Abramo.",
    "de": "Gott schafft Himmel und Erde und beginnt seinen Bund mit Abraham.",
    "pl": "Bóg stwarza niebo i ziemię i rozpoczyna przymierze z Abrahamem.",
    "vi": "Chúa tạo trời đất và bắt đầu giao ước với Abraham.",
    "tl": "Nilikha ng Diyos ang langit at lupa at sinimulan ang tipan kay Abraham."
  },
  "exodus": {
    "en": "God frees Israel from Egypt and gives the Ten Commandments at Sinai.",
    "ko": "하나님께서 이스라엘을 이집트에서 해방하시고 시나이에서 십계명을 주십니다.",
    "es": "Dios libera a Israel de Egipto y entrega los Diez Mandamientos.",
    "fr": "Dieu libère Israël d'Égypte et donne les Dix Commandements.",
    "pt": "Dios libera a Israel de Egipto y entrega los Diez Mandamientos.",
    "it": "God frees Israel from Egypt and gives the Ten Commandments at Sinai.",
    "de": "God frees Israel from Egypt and gives the Ten Commandments at Sinai.",
    "pl": "God frees Israel from Egypt and gives the Ten Commandments at Sinai.",
    "vi": "God frees Israel from Egypt and gives the Ten Commandments at Sinai.",
    "tl": "God frees Israel from Egypt and gives the Ten Commandments at Sinai."
  },
  "leviticus": {
    "en": "God teaches Israel how to worship and live as his holy people.",
    "ko": "이스라엘이 거룩한 백성으로 예배하고 살 길을 배웁니다.",
    "es": "God teaches Israel how to worship and live as his holy people.",
    "fr": "God teaches Israel how to worship and live as his holy people.",
    "pt": "God teaches Israel how to worship and live as his holy people.",
    "it": "God teaches Israel how to worship and live as his holy people.",
    "de": "God teaches Israel how to worship and live as his holy people.",
    "pl": "God teaches Israel how to worship and live as his holy people.",
    "vi": "God teaches Israel how to worship and live as his holy people.",
    "tl": "God teaches Israel how to worship and live as his holy people."
  },
  "numbers": {
    "en": "Israel journeys through the desert toward the promised land.",
    "ko": "이스라엘이 광야를 지나 약속의 땅을 향해 갑니다.",
    "es": "Israel journeys through the desert toward the promised land.",
    "fr": "Israel journeys through the desert toward the promised land.",
    "pt": "Israel journeys through the desert toward the promised land.",
    "it": "Israel journeys through the desert toward the promised land.",
    "de": "Israel journeys through the desert toward the promised land.",
    "pl": "Israel journeys through the desert toward the promised land.",
    "vi": "Israel journeys through the desert toward the promised land.",
    "tl": "Israel journeys through the desert toward the promised land."
  },
  "deuteronomy": {
    "en": "Moses renews the Law and blesses Israel before they enter the land.",
    "ko": "모세가 율법을 다시 선포하고 백성을 축복합니다.",
    "es": "Moses renews the Law and blesses Israel before they enter the land.",
    "fr": "Moses renews the Law and blesses Israel before they enter the land.",
    "pt": "Moses renews the Law and blesses Israel before they enter the land.",
    "it": "Moses renews the Law and blesses Israel before they enter the land.",
    "de": "Moses renews the Law and blesses Israel before they enter the land.",
    "pl": "Moses renews the Law and blesses Israel before they enter the land.",
    "vi": "Moses renews the Law and blesses Israel before they enter the land.",
    "tl": "Moses renews the Law and blesses Israel before they enter the land."
  },
  "josue": {
    "en": "Joshua leads Israel into the promised land.",
    "ko": "여호수아가 이스라엘을 약속의 땅으로 인도합니다.",
    "es": "Joshua leads Israel into the promised land.",
    "fr": "Joshua leads Israel into the promised land.",
    "pt": "Joshua leads Israel into the promised land.",
    "it": "Joshua leads Israel into the promised land.",
    "de": "Joshua leads Israel into the promised land.",
    "pl": "Joshua leads Israel into the promised land.",
    "vi": "Joshua leads Israel into the promised land.",
    "tl": "Joshua leads Israel into the promised land."
  },
  "judges": {
    "en": "Judges deliver Israel when the people turn back to God.",
    "ko": "판관들이 백성이 돌아올 때 이스라엘을 구원합니다.",
    "es": "Judges deliver Israel when the people turn back to God.",
    "fr": "Judges deliver Israel when the people turn back to God.",
    "pt": "Judges deliver Israel when the people turn back to God.",
    "it": "Judges deliver Israel when the people turn back to God.",
    "de": "Judges deliver Israel when the people turn back to God.",
    "pl": "Judges deliver Israel when the people turn back to God.",
    "vi": "Judges deliver Israel when the people turn back to God.",
    "tl": "Judges deliver Israel when the people turn back to God."
  },
  "ruth": {
    "en": "Ruth's faithful love leads her into the family of David.",
    "ko": "룻의 충실한 사랑이 다윗 가문으로 이어집니다.",
    "es": "Ruth's faithful love leads her into the family of David.",
    "fr": "Ruth's faithful love leads her into the family of David.",
    "pt": "Ruth's faithful love leads her into the family of David.",
    "it": "Ruth's faithful love leads her into the family of David.",
    "de": "Ruth's faithful love leads her into the family of David.",
    "pl": "Ruth's faithful love leads her into the family of David.",
    "vi": "Ruth's faithful love leads her into the family of David.",
    "tl": "Ruth's faithful love leads her into the family of David."
  },
  "1-kings-samuel": {
    "en": "Samuel anoints Saul and David as kings of Israel.",
    "ko": "사무엘은 사울과 다윗에게 기름을 부어 왕으로 세웁니다.",
    "es": "Samuel anoints Saul and David as kings of Israel.",
    "fr": "Samuel anoints Saul and David as kings of Israel.",
    "pt": "Samuel anoints Saul and David as kings of Israel.",
    "it": "Samuel anoints Saul and David as kings of Israel.",
    "de": "Samuel anoints Saul and David as kings of Israel.",
    "pl": "Samuel anoints Saul and David as kings of Israel.",
    "vi": "Samuel anoints Saul and David as kings of Israel.",
    "tl": "Samuel anoints Saul and David as kings of Israel."
  },
  "2-kings-samuel": {
    "en": "David becomes king and prepares a kingdom for God.",
    "ko": "다윗이 왕이 되어 하느님 나라를 준비합니다.",
    "es": "David becomes king and prepares a kingdom for God.",
    "fr": "David becomes king and prepares a kingdom for God.",
    "pt": "David becomes king and prepares a kingdom for God.",
    "it": "David becomes king and prepares a kingdom for God.",
    "de": "David becomes king and prepares a kingdom for God.",
    "pl": "David becomes king and prepares a kingdom for God.",
    "vi": "David becomes king and prepares a kingdom for God.",
    "tl": "David becomes king and prepares a kingdom for God."
  },
  "3-kings": {
    "en": "Solomon builds the Temple; later kings struggle with idolatry.",
    "ko": "솔로몬이 성전을 짓고, 이후 왕들은 우상 숭배와 씨름합니다.",
    "es": "Solomon builds the Temple; later kings struggle with idolatry.",
    "fr": "Solomon builds the Temple; later kings struggle with idolatry.",
    "pt": "Solomon builds the Temple; later kings struggle with idolatry.",
    "it": "Solomon builds the Temple; later kings struggle with idolatry.",
    "de": "Solomon builds the Temple; later kings struggle with idolatry.",
    "pl": "Solomon builds the Temple; later kings struggle with idolatry.",
    "vi": "Solomon builds the Temple; later kings struggle with idolatry.",
    "tl": "Solomon builds the Temple; later kings struggle with idolatry."
  },
  "4-kings": {
    "en": "Israel and Judah face prophets, exile, and God's mercy.",
    "ko": "이스라엘과 유다는 예언자, 유배, 자비를 맞닥뜨립니다.",
    "es": "Israel and Judah face prophets, exile, and God's mercy.",
    "fr": "Israel and Judah face prophets, exile, and God's mercy.",
    "pt": "Israel and Judah face prophets, exile, and God's mercy.",
    "it": "Israel and Judah face prophets, exile, and God's mercy.",
    "de": "Israel and Judah face prophets, exile, and God's mercy.",
    "pl": "Israel and Judah face prophets, exile, and God's mercy.",
    "vi": "Israel and Judah face prophets, exile, and God's mercy.",
    "tl": "Israel and Judah face prophets, exile, and God's mercy."
  },
  "1-paralipomenon": {
    "en": "Genealogies and David's reign in worship and prayer.",
    "ko": "족보와 다윗 왕의 예배와 기도가 기록됩니다.",
    "es": "Genealogies and David's reign in worship and prayer.",
    "fr": "Genealogies and David's reign in worship and prayer.",
    "pt": "Genealogies and David's reign in worship and prayer.",
    "it": "Genealogies and David's reign in worship and prayer.",
    "de": "Genealogies and David's reign in worship and prayer.",
    "pl": "Genealogies and David's reign in worship and prayer.",
    "vi": "Genealogies and David's reign in worship and prayer.",
    "tl": "Genealogies and David's reign in worship and prayer."
  },
  "2-paralipomenon": {
    "en": "Solomon's Temple and the faith of Judah's kings.",
    "ko": "솔로몬의 성전과 유다 왕들의 신앙이 다뤄집니다.",
    "es": "Solomon's Temple and the faith of Judah's kings.",
    "fr": "Solomon's Temple and the faith of Judah's kings.",
    "pt": "Solomon's Temple and the faith of Judah's kings.",
    "it": "Solomon's Temple and the faith of Judah's kings.",
    "de": "Solomon's Temple and the faith of Judah's kings.",
    "pl": "Solomon's Temple and the faith of Judah's kings.",
    "vi": "Solomon's Temple and the faith of Judah's kings.",
    "tl": "Solomon's Temple and the faith of Judah's kings."
  },
  "1-esdras": {
    "en": "Exiles return and rebuild the Temple in Jerusalem.",
    "ko": "포로 귀환자들이 예루살렘 성전을 재건합니다.",
    "es": "Exiles return and rebuild the Temple in Jerusalem.",
    "fr": "Exiles return and rebuild the Temple in Jerusalem.",
    "pt": "Exiles return and rebuild the Temple in Jerusalem.",
    "it": "Exiles return and rebuild the Temple in Jerusalem.",
    "de": "Exiles return and rebuild the Temple in Jerusalem.",
    "pl": "Exiles return and rebuild the Temple in Jerusalem.",
    "vi": "Exiles return and rebuild the Temple in Jerusalem.",
    "tl": "Exiles return and rebuild the Temple in Jerusalem."
  },
  "2-esdras-nehemias": {
    "en": "Nehemiah rebuilds Jerusalem's walls and renews the covenant.",
    "ko": "느헤미야가 성벽을 재건하고 언약을 새롭게 합니다.",
    "es": "Nehemiah rebuilds Jerusalem's walls and renews the covenant.",
    "fr": "Nehemiah rebuilds Jerusalem's walls and renews the covenant.",
    "pt": "Nehemiah rebuilds Jerusalem's walls and renews the covenant.",
    "it": "Nehemiah rebuilds Jerusalem's walls and renews the covenant.",
    "de": "Nehemiah rebuilds Jerusalem's walls and renews the covenant.",
    "pl": "Nehemiah rebuilds Jerusalem's walls and renews the covenant.",
    "vi": "Nehemiah rebuilds Jerusalem's walls and renews the covenant.",
    "tl": "Nehemiah rebuilds Jerusalem's walls and renews the covenant."
  },
  "tobias": {
    "en": "Tobit and Tobias show faith, family love, and God's guidance.",
    "ko": "토빗과 토비아는 믿음과 가족 사랑으로 하느님의 인도를 경험합니다.",
    "es": "Tobit and Tobias show faith, family love, and God's guidance.",
    "fr": "Tobit and Tobias show faith, family love, and God's guidance.",
    "pt": "Tobit and Tobias show faith, family love, and God's guidance.",
    "it": "Tobit and Tobias show faith, family love, and God's guidance.",
    "de": "Tobit and Tobias show faith, family love, and God's guidance.",
    "pl": "Tobit and Tobias show faith, family love, and God's guidance.",
    "vi": "Tobit and Tobias show faith, family love, and God's guidance.",
    "tl": "Tobit and Tobias show faith, family love, and God's guidance."
  },
  "judith": {
    "en": "Judith saves her people through courage and trust in God.",
    "ko": "유딧은 용기와 신뢰로 백성을 구합니다.",
    "es": "Judith saves her people through courage and trust in God.",
    "fr": "Judith saves her people through courage and trust in God.",
    "pt": "Judith saves her people through courage and trust in God.",
    "it": "Judith saves her people through courage and trust in God.",
    "de": "Judith saves her people through courage and trust in God.",
    "pl": "Judith saves her people through courage and trust in God.",
    "vi": "Judith saves her people through courage and trust in God.",
    "tl": "Judith saves her people through courage and trust in God."
  },
  "esther": {
    "en": "Esther risks her life to save the Jewish people.",
    "ko": "에스테르는 민족을 구하기 위해 목숨을 걸습니다.",
    "es": "Esther risks her life to save the Jewish people.",
    "fr": "Esther risks her life to save the Jewish people.",
    "pt": "Esther risks her life to save the Jewish people.",
    "it": "Esther risks her life to save the Jewish people.",
    "de": "Esther risks her life to save the Jewish people.",
    "pl": "Esther risks her life to save the Jewish people.",
    "vi": "Esther risks her life to save the Jewish people.",
    "tl": "Esther risks her life to save the Jewish people."
  },
  "job": {
    "en": "Job wrestles with suffering and meets God's wisdom.",
    "ko": "욥은 고난 속에서 하느님의 지혜를 만납니다.",
    "es": "Job wrestles with suffering and meets God's wisdom.",
    "fr": "Job wrestles with suffering and meets God's wisdom.",
    "pt": "Job wrestles with suffering and meets God's wisdom.",
    "it": "Job wrestles with suffering and meets God's wisdom.",
    "de": "Job wrestles with suffering and meets God's wisdom.",
    "pl": "Job wrestles with suffering and meets God's wisdom.",
    "vi": "Job wrestles with suffering and meets God's wisdom.",
    "tl": "Job wrestles with suffering and meets God's wisdom."
  },
  "psalms": {
    "en": "Prayers and songs of praise, lament, and trust in God.",
    "ko": "찬양과 탄원, 신뢰의 기도와 노래 모음입니다.",
    "es": "Oraciones y cantos de alabanza, lamento y confianza en Dios.",
    "fr": "Prières et cantiques de louange, de lamentation et de confiance.",
    "pt": "Oraciones y cantos de alabanza, lamento y confianza en Dios.",
    "it": "Prayers and songs of praise, lament, and trust in God.",
    "de": "Prayers and songs of praise, lament, and trust in God.",
    "pl": "Prayers and songs of praise, lament, and trust in God.",
    "vi": "Prayers and songs of praise, lament, and trust in God.",
    "tl": "Prayers and songs of praise, lament, and trust in God."
  },
  "proverbs": {
    "en": "Practical wisdom for living with fear of the Lord.",
    "ko": "주를 경외하며 사는 실천적 지혜를 가르칩니다.",
    "es": "Practical wisdom for living with fear of the Lord.",
    "fr": "Practical wisdom for living with fear of the Lord.",
    "pt": "Practical wisdom for living with fear of the Lord.",
    "it": "Practical wisdom for living with fear of the Lord.",
    "de": "Practical wisdom for living with fear of the Lord.",
    "pl": "Practical wisdom for living with fear of the Lord.",
    "vi": "Practical wisdom for living with fear of the Lord.",
    "tl": "Practical wisdom for living with fear of the Lord."
  },
  "ecclesiastes": {
    "en": "Reflection on life's meaning under God's sovereignty.",
    "ko": "하느님 주권 아래 인생의 의미를 묻습니다.",
    "es": "Reflection on life's meaning under God's sovereignty.",
    "fr": "Reflection on life's meaning under God's sovereignty.",
    "pt": "Reflection on life's meaning under God's sovereignty.",
    "it": "Reflection on life's meaning under God's sovereignty.",
    "de": "Reflection on life's meaning under God's sovereignty.",
    "pl": "Reflection on life's meaning under God's sovereignty.",
    "vi": "Reflection on life's meaning under God's sovereignty.",
    "tl": "Reflection on life's meaning under God's sovereignty."
  },
  "canticle-of-canticles": {
    "en": "A song of married love that images God's love.",
    "ko": "결혼 사랑의 노래로 하느님 사랑을 비춥니다.",
    "es": "A song of married love that images God's love.",
    "fr": "A song of married love that images God's love.",
    "pt": "A song of married love that images God's love.",
    "it": "A song of married love that images God's love.",
    "de": "A song of married love that images God's love.",
    "pl": "A song of married love that images God's love.",
    "vi": "A song of married love that images God's love.",
    "tl": "A song of married love that images God's love."
  },
  "wisdom": {
    "en": "Wisdom leads to life and friendship with God.",
    "ko": "지혜는 생명과 하느님과의 우정으로 이끕니다.",
    "es": "Wisdom leads to life and friendship with God.",
    "fr": "Wisdom leads to life and friendship with God.",
    "pt": "Wisdom leads to life and friendship with God.",
    "it": "Wisdom leads to life and friendship with God.",
    "de": "Wisdom leads to life and friendship with God.",
    "pl": "Wisdom leads to life and friendship with God.",
    "vi": "Wisdom leads to life and friendship with God.",
    "tl": "Wisdom leads to life and friendship with God."
  },
  "ecclesiasticus": {
    "en": "Sirach teaches wisdom for family, worship, and daily life.",
    "ko": "집회서는 가정, 예배, 일상의 지혜를 가르칩니다.",
    "es": "Sirach teaches wisdom for family, worship, and daily life.",
    "fr": "Sirach teaches wisdom for family, worship, and daily life.",
    "pt": "Sirach teaches wisdom for family, worship, and daily life.",
    "it": "Sirach teaches wisdom for family, worship, and daily life.",
    "de": "Sirach teaches wisdom for family, worship, and daily life.",
    "pl": "Sirach teaches wisdom for family, worship, and daily life.",
    "vi": "Sirach teaches wisdom for family, worship, and daily life.",
    "tl": "Sirach teaches wisdom for family, worship, and daily life."
  },
  "isaias": {
    "en": "Isaiah proclaims the Messiah and the hope of a new creation.",
    "ko": "이사야는 메시아와 새 창조의 희망을 선포합니다.",
    "es": "Isaiah proclaims the Messiah and the hope of a new creation.",
    "fr": "Isaiah proclaims the Messiah and the hope of a new creation.",
    "pt": "Isaiah proclaims the Messiah and the hope of a new creation.",
    "it": "Isaiah proclaims the Messiah and the hope of a new creation.",
    "de": "Isaiah proclaims the Messiah and the hope of a new creation.",
    "pl": "Isaiah proclaims the Messiah and the hope of a new creation.",
    "vi": "Isaiah proclaims the Messiah and the hope of a new creation.",
    "tl": "Isaiah proclaims the Messiah and the hope of a new creation."
  },
  "jeremias": {
    "en": "Jeremiah calls for repentance and promises a new covenant.",
    "ko": "예레미야는 회개를 촉구하고 새 언약을 약속합니다.",
    "es": "Jeremiah calls for repentance and promises a new covenant.",
    "fr": "Jeremiah calls for repentance and promises a new covenant.",
    "pt": "Jeremiah calls for repentance and promises a new covenant.",
    "it": "Jeremiah calls for repentance and promises a new covenant.",
    "de": "Jeremiah calls for repentance and promises a new covenant.",
    "pl": "Jeremiah calls for repentance and promises a new covenant.",
    "vi": "Jeremiah calls for repentance and promises a new covenant.",
    "tl": "Jeremiah calls for repentance and promises a new covenant."
  },
  "lamentations": {
    "en": "Poems mourning Jerusalem with hope in God's mercy.",
    "ko": "예루살렘의 애가와 자비에 대한 희망을 노래합니다.",
    "es": "Poems mourning Jerusalem with hope in God's mercy.",
    "fr": "Poems mourning Jerusalem with hope in God's mercy.",
    "pt": "Poems mourning Jerusalem with hope in God's mercy.",
    "it": "Poems mourning Jerusalem with hope in God's mercy.",
    "de": "Poems mourning Jerusalem with hope in God's mercy.",
    "pl": "Poems mourning Jerusalem with hope in God's mercy.",
    "vi": "Poems mourning Jerusalem with hope in God's mercy.",
    "tl": "Poems mourning Jerusalem with hope in God's mercy."
  },
  "baruch": {
    "en": "Prayers of exiles trusting God's justice and mercy.",
    "ko": "바룩은 유배 중 기도와 정의를 신뢰합니다.",
    "es": "Prayers of exiles trusting God's justice and mercy.",
    "fr": "Prayers of exiles trusting God's justice and mercy.",
    "pt": "Prayers of exiles trusting God's justice and mercy.",
    "it": "Prayers of exiles trusting God's justice and mercy.",
    "de": "Prayers of exiles trusting God's justice and mercy.",
    "pl": "Prayers of exiles trusting God's justice and mercy.",
    "vi": "Prayers of exiles trusting God's justice and mercy.",
    "tl": "Prayers of exiles trusting God's justice and mercy."
  },
  "ezechiel": {
    "en": "Ezekiel sees God's glory and promises a new heart for Israel.",
    "ko": "에제키엘은 하느님 영광과 새 마음을 약속합니다.",
    "es": "Ezekiel sees God's glory and promises a new heart for Israel.",
    "fr": "Ezekiel sees God's glory and promises a new heart for Israel.",
    "pt": "Ezekiel sees God's glory and promises a new heart for Israel.",
    "it": "Ezekiel sees God's glory and promises a new heart for Israel.",
    "de": "Ezekiel sees God's glory and promises a new heart for Israel.",
    "pl": "Ezekiel sees God's glory and promises a new heart for Israel.",
    "vi": "Ezekiel sees God's glory and promises a new heart for Israel.",
    "tl": "Ezekiel sees God's glory and promises a new heart for Israel."
  },
  "daniel": {
    "en": "Daniel remains faithful in exile; God rules all kingdoms.",
    "ko": "다니엘은 유배 중에도 충실하며 하느님께서 역사를 다스리심을 보여 줍니다.",
    "es": "Daniel remains faithful in exile; God rules all kingdoms.",
    "fr": "Daniel remains faithful in exile; God rules all kingdoms.",
    "pt": "Daniel remains faithful in exile; God rules all kingdoms.",
    "it": "Daniel remains faithful in exile; God rules all kingdoms.",
    "de": "Daniel remains faithful in exile; God rules all kingdoms.",
    "pl": "Daniel remains faithful in exile; God rules all kingdoms.",
    "vi": "Daniel remains faithful in exile; God rules all kingdoms.",
    "tl": "Daniel remains faithful in exile; God rules all kingdoms."
  },
  "osee": {
    "en": "Hosea shows God's faithful love for an unfaithful people.",
    "ko": "호세아는 불충실한 백성에게 하느님의 신실한 사랑을 보여 줍니다.",
    "es": "Hosea shows God's faithful love for an unfaithful people.",
    "fr": "Hosea shows God's faithful love for an unfaithful people.",
    "pt": "Hosea shows God's faithful love for an unfaithful people.",
    "it": "Hosea shows God's faithful love for an unfaithful people.",
    "de": "Hosea shows God's faithful love for an unfaithful people.",
    "pl": "Hosea shows God's faithful love for an unfaithful people.",
    "vi": "Hosea shows God's faithful love for an unfaithful people.",
    "tl": "Hosea shows God's faithful love for an unfaithful people."
  },
  "joel": {
    "en": "Joel calls for repentance and promises the Spirit's outpouring.",
    "ko": "요엘은 회개를 촉구하고 성령 부어 주심을 약속합니다.",
    "es": "Joel calls for repentance and promises the Spirit's outpouring.",
    "fr": "Joel calls for repentance and promises the Spirit's outpouring.",
    "pt": "Joel calls for repentance and promises the Spirit's outpouring.",
    "it": "Joel calls for repentance and promises the Spirit's outpouring.",
    "de": "Joel calls for repentance and promises the Spirit's outpouring.",
    "pl": "Joel calls for repentance and promises the Spirit's outpouring.",
    "vi": "Joel calls for repentance and promises the Spirit's outpouring.",
    "tl": "Joel calls for repentance and promises the Spirit's outpouring."
  },
  "amos": {
    "en": "Amos demands justice for the poor and true worship.",
    "ko": "아모스는 가난한 이를 위한 정의와 참된 예배를 요구합니다.",
    "es": "Amos demands justice for the poor and true worship.",
    "fr": "Amos demands justice for the poor and true worship.",
    "pt": "Amos demands justice for the poor and true worship.",
    "it": "Amos demands justice for the poor and true worship.",
    "de": "Amos demands justice for the poor and true worship.",
    "pl": "Amos demands justice for the poor and true worship.",
    "vi": "Amos demands justice for the poor and true worship.",
    "tl": "Amos demands justice for the poor and true worship."
  },
  "abdias": {
    "en": "Obadiah announces judgment and hope for God's people.",
    "ko": "오바디야는 심판과 하느님 백성의 희망을 선포합니다.",
    "es": "Obadiah announces judgment and hope for God's people.",
    "fr": "Obadiah announces judgment and hope for God's people.",
    "pt": "Obadiah announces judgment and hope for God's people.",
    "it": "Obadiah announces judgment and hope for God's people.",
    "de": "Obadiah announces judgment and hope for God's people.",
    "pl": "Obadiah announces judgment and hope for God's people.",
    "vi": "Obadiah announces judgment and hope for God's people.",
    "tl": "Obadiah announces judgment and hope for God's people."
  },
  "jonas": {
    "en": "Jonah learns that God's mercy reaches all nations.",
    "ko": "요나는 하느님 자비가 모든 민족에게 미침을 배웁니다.",
    "es": "Jonah learns that God's mercy reaches all nations.",
    "fr": "Jonah learns that God's mercy reaches all nations.",
    "pt": "Jonah learns that God's mercy reaches all nations.",
    "it": "Jonah learns that God's mercy reaches all nations.",
    "de": "Jonah learns that God's mercy reaches all nations.",
    "pl": "Jonah learns that God's mercy reaches all nations.",
    "vi": "Jonah learns that God's mercy reaches all nations.",
    "tl": "Jonah learns that God's mercy reaches all nations."
  },
  "micheas": {
    "en": "Micah foretells Bethlehem and calls for justice and mercy.",
    "ko": "미카는 베들레헴과 정의·자비를 예고합니다.",
    "es": "Micah foretells Bethlehem and calls for justice and mercy.",
    "fr": "Micah foretells Bethlehem and calls for justice and mercy.",
    "pt": "Micah foretells Bethlehem and calls for justice and mercy.",
    "it": "Micah foretells Bethlehem and calls for justice and mercy.",
    "de": "Micah foretells Bethlehem and calls for justice and mercy.",
    "pl": "Micah foretells Bethlehem and calls for justice and mercy.",
    "vi": "Micah foretells Bethlehem and calls for justice and mercy.",
    "tl": "Micah foretells Bethlehem and calls for justice and mercy."
  },
  "nahum": {
    "en": "Nahum announces the fall of cruel Nineveh.",
    "ko": "나훔은 잔혹한 니니웨의 멸망을 선포합니다.",
    "es": "Nahum announces the fall of cruel Nineveh.",
    "fr": "Nahum announces the fall of cruel Nineveh.",
    "pt": "Nahum announces the fall of cruel Nineveh.",
    "it": "Nahum announces the fall of cruel Nineveh.",
    "de": "Nahum announces the fall of cruel Nineveh.",
    "pl": "Nahum announces the fall of cruel Nineveh.",
    "vi": "Nahum announces the fall of cruel Nineveh.",
    "tl": "Nahum announces the fall of cruel Nineveh."
  },
  "habacuc": {
    "en": "Habakkuk learns to live by faith while awaiting God's justice.",
    "ko": "하바쿡은 믿음으로 살며 정의를 기다립니다.",
    "es": "Habakkuk learns to live by faith while awaiting God's justice.",
    "fr": "Habakkuk learns to live by faith while awaiting God's justice.",
    "pt": "Habakkuk learns to live by faith while awaiting God's justice.",
    "it": "Habakkuk learns to live by faith while awaiting God's justice.",
    "de": "Habakkuk learns to live by faith while awaiting God's justice.",
    "pl": "Habakkuk learns to live by faith while awaiting God's justice.",
    "vi": "Habakkuk learns to live by faith while awaiting God's justice.",
    "tl": "Habakkuk learns to live by faith while awaiting God's justice."
  },
  "sophonias": {
    "en": "Zephaniah warns of judgment and promises a humble remnant.",
    "ko": "스바니야는 심판과 겸손한 남은 자를 약속합니다.",
    "es": "Zephaniah warns of judgment and promises a humble remnant.",
    "fr": "Zephaniah warns of judgment and promises a humble remnant.",
    "pt": "Zephaniah warns of judgment and promises a humble remnant.",
    "it": "Zephaniah warns of judgment and promises a humble remnant.",
    "de": "Zephaniah warns of judgment and promises a humble remnant.",
    "pl": "Zephaniah warns of judgment and promises a humble remnant.",
    "vi": "Zephaniah warns of judgment and promises a humble remnant.",
    "tl": "Zephaniah warns of judgment and promises a humble remnant."
  },
  "aggeus": {
    "en": "Haggai urges the people to rebuild the Temple.",
    "ko": "하까이는 성전 재건을 촉구합니다.",
    "es": "Haggai urges the people to rebuild the Temple.",
    "fr": "Haggai urges the people to rebuild the Temple.",
    "pt": "Haggai urges the people to rebuild the Temple.",
    "it": "Haggai urges the people to rebuild the Temple.",
    "de": "Haggai urges the people to rebuild the Temple.",
    "pl": "Haggai urges the people to rebuild the Temple.",
    "vi": "Haggai urges the people to rebuild the Temple.",
    "tl": "Haggai urges the people to rebuild the Temple."
  },
  "zacharias": {
    "en": "Zechariah encourages the returned exiles and foretells the Messiah.",
    "ko": "즈카리야는 귀환 백성을 격려하고 메시아를 예고합니다.",
    "es": "Zechariah encourages the returned exiles and foretells the Messiah.",
    "fr": "Zechariah encourages the returned exiles and foretells the Messiah.",
    "pt": "Zechariah encourages the returned exiles and foretells the Messiah.",
    "it": "Zechariah encourages the returned exiles and foretells the Messiah.",
    "de": "Zechariah encourages the returned exiles and foretells the Messiah.",
    "pl": "Zechariah encourages the returned exiles and foretells the Messiah.",
    "vi": "Zechariah encourages the returned exiles and foretells the Messiah.",
    "tl": "Zechariah encourages the returned exiles and foretells the Messiah."
  },
  "malachias": {
    "en": "Malachi calls Israel to sincere worship before the Lord comes.",
    "ko": "말라키는 주 오심 전 진실한 예배를 촉구합니다.",
    "es": "Malachi calls Israel to sincere worship before the Lord comes.",
    "fr": "Malachi calls Israel to sincere worship before the Lord comes.",
    "pt": "Malachi calls Israel to sincere worship before the Lord comes.",
    "it": "Malachi calls Israel to sincere worship before the Lord comes.",
    "de": "Malachi calls Israel to sincere worship before the Lord comes.",
    "pl": "Malachi calls Israel to sincere worship before the Lord comes.",
    "vi": "Malachi calls Israel to sincere worship before the Lord comes.",
    "tl": "Malachi calls Israel to sincere worship before the Lord comes."
  },
  "1-machabees": {
    "en": "The Maccabees defend the Temple and Jewish faith.",
    "ko": "마카베오 가문이 성전과 신앙을 지킵니다.",
    "es": "The Maccabees defend the Temple and Jewish faith.",
    "fr": "The Maccabees defend the Temple and Jewish faith.",
    "pt": "The Maccabees defend the Temple and Jewish faith.",
    "it": "The Maccabees defend the Temple and Jewish faith.",
    "de": "The Maccabees defend the Temple and Jewish faith.",
    "pl": "The Maccabees defend the Temple and Jewish faith.",
    "vi": "The Maccabees defend the Temple and Jewish faith.",
    "tl": "The Maccabees defend the Temple and Jewish faith."
  },
  "2-machabees": {
    "en": "Martyrs witness to resurrection hope and Temple purity.",
    "ko": "순교자들이 부활 희망과 성전 정결을 증언합니다.",
    "es": "Martyrs witness to resurrection hope and Temple purity.",
    "fr": "Martyrs witness to resurrection hope and Temple purity.",
    "pt": "Martyrs witness to resurrection hope and Temple purity.",
    "it": "Martyrs witness to resurrection hope and Temple purity.",
    "de": "Martyrs witness to resurrection hope and Temple purity.",
    "pl": "Martyrs witness to resurrection hope and Temple purity.",
    "vi": "Martyrs witness to resurrection hope and Temple purity.",
    "tl": "Martyrs witness to resurrection hope and Temple purity."
  },
  "matthew": {
    "en": "Matthew presents Jesus as the fulfillment of the Law and prophets.",
    "ko": "마태오는 예수님을 율법과 예언의 완성으로 보여 줍니다.",
    "es": "Mateo presenta a Jesús como cumplimiento de la Ley y los profetas.",
    "fr": "Matthieu présente Jésus comme l'accomplissement de la Loi et des prophètes.",
    "pt": "Mateo presenta a Jesús como cumplimiento de la Ley y los profetas.",
    "it": "Matteo presenta Gesù come adempimento della Legge e dei profeti.",
    "de": "Matthäus zeigt Jesus als Erfüllung von Gesetz und Propheten.",
    "pl": "Mateusz ukazuje Jezusa jako wypełnienie Prawa i proroków.",
    "vi": "Matthêô trình bày Chúa Giêsu là sự hoàn thành Luật và các tiên tri.",
    "tl": "Ipinapakita ni Mateo si Jesus bilang katuparan ng Kautusan at mga propeta."
  },
  "mark": {
    "en": "Mark shows Jesus as the powerful Son of God who serves and saves.",
    "ko": "마르코는 섬기시며 구원하시는 하느님의 아들을 보여 줍니다.",
    "es": "Marcos muestra a Jesús, Hijo de Dios, que sirve y salva.",
    "fr": "Marc montre Jésus, Fils de Dieu, qui sert et sauve.",
    "pt": "Marcos muestra a Jesús, Hijo de Dios, que sirve y salva.",
    "it": "Marco mostra Gesù, Figlio di Dio, che serve e salva.",
    "de": "Markus zeigt Jesus, den dienenden und rettenden Gottessohn.",
    "pl": "Marek ukazuje Jezusa, Syna Bożego, który służy i zbawia.",
    "vi": "Mác trình bày Chúa Giêsu, Con Thiên Chúa, phục vụ và cứu độ.",
    "tl": "Ipinapakita ni Marcos si Jesus, Anak ng Diyos, na naglilingkod at nagligtas."
  },
  "luke": {
    "en": "Luke emphasizes mercy, prayer, and joy in Christ's salvation.",
    "ko": "루카는 자비, 기도, 구원의 기쁨을 강조합니다.",
    "es": "Lucas destaca la misericordia, la oración y la alegría de la salvación.",
    "fr": "Luc met en avant la miséricorde, la prière et la joie du salut.",
    "pt": "Lucas destaca la misericordia, la oración y la alegría de la salvación.",
    "it": "Luke emphasizes mercy, prayer, and joy in Christ's salvation.",
    "de": "Luke emphasizes mercy, prayer, and joy in Christ's salvation.",
    "pl": "Luke emphasizes mercy, prayer, and joy in Christ's salvation.",
    "vi": "Luke emphasizes mercy, prayer, and joy in Christ's salvation.",
    "tl": "Luke emphasizes mercy, prayer, and joy in Christ's salvation."
  },
  "john": {
    "en": "John proclaims Jesus as the eternal Word made flesh.",
    "ko": "요한은 영원한 말씀이신 예수님을 선포합니다.",
    "es": "Juan proclama a Jesús como el Verbo eterno hecho carne.",
    "fr": "Jean proclame Jésus comme le Verbe éternel fait chair.",
    "pt": "Juan proclama a Jesús como el Verbo eterno hecho carne.",
    "it": "Giovanni proclama Gesù come Verbo eterno fatto carne.",
    "de": "Johannes verkündet Jesus als das ewige Wort im Fleisch.",
    "pl": "John proclaims Jesus as the eternal Word made flesh.",
    "vi": "John proclaims Jesus as the eternal Word made flesh.",
    "tl": "John proclaims Jesus as the eternal Word made flesh."
  },
  "acts": {
    "en": "The Holy Spirit empowers the apostles to spread the Gospel.",
    "ko": "성령께서 사도들을 통해 복음을 퍼뜨리십니다.",
    "es": "El Espíritu Santo impulsa a los apóstoles a predicar el Evangelio.",
    "fr": "L'Esprit Saint pousse les apôtres à répandre l'Évangile.",
    "pt": "El Espíritu Santo impulsa a los apóstoles a predicar el Evangelio.",
    "it": "The Holy Spirit empowers the apostles to spread the Gospel.",
    "de": "The Holy Spirit empowers the apostles to spread the Gospel.",
    "pl": "The Holy Spirit empowers the apostles to spread the Gospel.",
    "vi": "The Holy Spirit empowers the apostles to spread the Gospel.",
    "tl": "The Holy Spirit empowers the apostles to spread the Gospel."
  },
  "romans": {
    "en": "Paul explains justification by faith and life in the Spirit.",
    "ko": "바오로는 믿음으로 의롭게 됨과 성령 안의 삶을 설명합니다.",
    "es": "Pablo explica la justificación por la fe y la vida en el Espíritu.",
    "fr": "Paul explique la justification par la foi et la vie dans l'Esprit.",
    "pt": "Pablo explica la justificación por la fe y la vida en el Espíritu.",
    "it": "Paul explains justification by faith and life in the Spirit.",
    "de": "Paul explains justification by faith and life in the Spirit.",
    "pl": "Paul explains justification by faith and life in the Spirit.",
    "vi": "Paul explains justification by faith and life in the Spirit.",
    "tl": "Paul explains justification by faith and life in the Spirit."
  },
  "1-corinthians": {
    "en": "Paul teaches unity, love, and worthy Eucharistic worship.",
    "ko": "바오로는 일치, 사랑, 거룩한 성체 예배를 가르칩니다.",
    "es": "Paul teaches unity, love, and worthy Eucharistic worship.",
    "fr": "Paul teaches unity, love, and worthy Eucharistic worship.",
    "pt": "Paul teaches unity, love, and worthy Eucharistic worship.",
    "it": "Paul teaches unity, love, and worthy Eucharistic worship.",
    "de": "Paul teaches unity, love, and worthy Eucharistic worship.",
    "pl": "Paul teaches unity, love, and worthy Eucharistic worship.",
    "vi": "Paul teaches unity, love, and worthy Eucharistic worship.",
    "tl": "Paul teaches unity, love, and worthy Eucharistic worship."
  },
  "2-corinthians": {
    "en": "Paul defends his ministry and God's power in weakness.",
    "ko": "바오로는 약함 속 하느님 권능을 증언합니다.",
    "es": "Paul defends his ministry and God's power in weakness.",
    "fr": "Paul defends his ministry and God's power in weakness.",
    "pt": "Paul defends his ministry and God's power in weakness.",
    "it": "Paul defends his ministry and God's power in weakness.",
    "de": "Paul defends his ministry and God's power in weakness.",
    "pl": "Paul defends his ministry and God's power in weakness.",
    "vi": "Paul defends his ministry and God's power in weakness.",
    "tl": "Paul defends his ministry and God's power in weakness."
  },
  "galatians": {
    "en": "Paul proclaims freedom in Christ against false gospel.",
    "ko": "바오로는 그리스도 안의 자유를 선포합니다.",
    "es": "Paul proclaims freedom in Christ against false gospel.",
    "fr": "Paul proclaims freedom in Christ against false gospel.",
    "pt": "Paul proclaims freedom in Christ against false gospel.",
    "it": "Paul proclaims freedom in Christ against false gospel.",
    "de": "Paul proclaims freedom in Christ against false gospel.",
    "pl": "Paul proclaims freedom in Christ against false gospel.",
    "vi": "Paul proclaims freedom in Christ against false gospel.",
    "tl": "Paul proclaims freedom in Christ against false gospel."
  },
  "ephesians": {
    "en": "Paul describes the Church as Christ's body and calls for unity.",
    "ko": "교회는 그리스도의 몸이며 일치가 요청됩니다.",
    "es": "Paul describes the Church as Christ's body and calls for unity.",
    "fr": "Paul describes the Church as Christ's body and calls for unity.",
    "pt": "Paul describes the Church as Christ's body and calls for unity.",
    "it": "Paul describes the Church as Christ's body and calls for unity.",
    "de": "Paul describes the Church as Christ's body and calls for unity.",
    "pl": "Paul describes the Church as Christ's body and calls for unity.",
    "vi": "Paul describes the Church as Christ's body and calls for unity.",
    "tl": "Paul describes the Church as Christ's body and calls for unity."
  },
  "philippians": {
    "en": "Paul rejoices in Christ from prison and urges humble love.",
    "ko": "바오로는 감옥에서도 그리스도 안에서 기뻐합니다.",
    "es": "Paul rejoices in Christ from prison and urges humble love.",
    "fr": "Paul rejoices in Christ from prison and urges humble love.",
    "pt": "Paul rejoices in Christ from prison and urges humble love.",
    "it": "Paul rejoices in Christ from prison and urges humble love.",
    "de": "Paul rejoices in Christ from prison and urges humble love.",
    "pl": "Paul rejoices in Christ from prison and urges humble love.",
    "vi": "Paul rejoices in Christ from prison and urges humble love.",
    "tl": "Paul rejoices in Christ from prison and urges humble love."
  },
  "colossians": {
    "en": "Christ is supreme; believers are called to holy living.",
    "ko": "그리스도는 최고이시며 거룩한 삶이 요청됩니다.",
    "es": "Christ is supreme; believers are called to holy living.",
    "fr": "Christ is supreme; believers are called to holy living.",
    "pt": "Christ is supreme; believers are called to holy living.",
    "it": "Christ is supreme; believers are called to holy living.",
    "de": "Christ is supreme; believers are called to holy living.",
    "pl": "Christ is supreme; believers are called to holy living.",
    "vi": "Christ is supreme; believers are called to holy living.",
    "tl": "Christ is supreme; believers are called to holy living."
  },
  "1-thessalonians": {
    "en": "Paul encourages hope in Christ's return and holy living.",
    "ko": "주님 재림의 희망과 거룩한 삶을 격려합니다.",
    "es": "Paul encourages hope in Christ's return and holy living.",
    "fr": "Paul encourages hope in Christ's return and holy living.",
    "pt": "Paul encourages hope in Christ's return and holy living.",
    "it": "Paul encourages hope in Christ's return and holy living.",
    "de": "Paul encourages hope in Christ's return and holy living.",
    "pl": "Paul encourages hope in Christ's return and holy living.",
    "vi": "Paul encourages hope in Christ's return and holy living.",
    "tl": "Paul encourages hope in Christ's return and holy living."
  },
  "2-thessalonians": {
    "en": "Paul corrects confusion about the Lord's coming.",
    "ko": "주님 오심에 대한 오해를 바로잡습니다.",
    "es": "Paul corrects confusion about the Lord's coming.",
    "fr": "Paul corrects confusion about the Lord's coming.",
    "pt": "Paul corrects confusion about the Lord's coming.",
    "it": "Paul corrects confusion about the Lord's coming.",
    "de": "Paul corrects confusion about the Lord's coming.",
    "pl": "Paul corrects confusion about the Lord's coming.",
    "vi": "Paul corrects confusion about the Lord's coming.",
    "tl": "Paul corrects confusion about the Lord's coming."
  },
  "1-timothy": {
    "en": "Paul guides Timothy in leading the Church faithfully.",
    "ko": "바오로는 티모테오에게 충실한 지도를 권합니다.",
    "es": "Paul guides Timothy in leading the Church faithfully.",
    "fr": "Paul guides Timothy in leading the Church faithfully.",
    "pt": "Paul guides Timothy in leading the Church faithfully.",
    "it": "Paul guides Timothy in leading the Church faithfully.",
    "de": "Paul guides Timothy in leading the Church faithfully.",
    "pl": "Paul guides Timothy in leading the Church faithfully.",
    "vi": "Paul guides Timothy in leading the Church faithfully.",
    "tl": "Paul guides Timothy in leading the Church faithfully."
  },
  "2-timothy": {
    "en": "Paul charges Timothy to preach the word with courage.",
    "ko": "바오로는 말씀을 담대히 전하라고 명합니다.",
    "es": "Paul charges Timothy to preach the word with courage.",
    "fr": "Paul charges Timothy to preach the word with courage.",
    "pt": "Paul charges Timothy to preach the word with courage.",
    "it": "Paul charges Timothy to preach the word with courage.",
    "de": "Paul charges Timothy to preach the word with courage.",
    "pl": "Paul charges Timothy to preach the word with courage.",
    "vi": "Paul charges Timothy to preach the word with courage.",
    "tl": "Paul charges Timothy to preach the word with courage."
  },
  "titus": {
    "en": "Paul instructs Titus to appoint leaders and teach sound doctrine.",
    "ko": "바오로는 티토에게 지도자와 바른 교리를 가르칩니다.",
    "es": "Paul instructs Titus to appoint leaders and teach sound doctrine.",
    "fr": "Paul instructs Titus to appoint leaders and teach sound doctrine.",
    "pt": "Paul instructs Titus to appoint leaders and teach sound doctrine.",
    "it": "Paul instructs Titus to appoint leaders and teach sound doctrine.",
    "de": "Paul instructs Titus to appoint leaders and teach sound doctrine.",
    "pl": "Paul instructs Titus to appoint leaders and teach sound doctrine.",
    "vi": "Paul instructs Titus to appoint leaders and teach sound doctrine.",
    "tl": "Paul instructs Titus to appoint leaders and teach sound doctrine."
  },
  "philemon": {
    "en": "Paul appeals for the Christian reconciliation of Onesimus.",
    "ko": "바오로는 오네시모의 화해를 간청합니다.",
    "es": "Paul appeals for the Christian reconciliation of Onesimus.",
    "fr": "Paul appeals for the Christian reconciliation of Onesimus.",
    "pt": "Paul appeals for the Christian reconciliation of Onesimus.",
    "it": "Paul appeals for the Christian reconciliation of Onesimus.",
    "de": "Paul appeals for the Christian reconciliation of Onesimus.",
    "pl": "Paul appeals for the Christian reconciliation of Onesimus.",
    "vi": "Paul appeals for the Christian reconciliation of Onesimus.",
    "tl": "Paul appeals for the Christian reconciliation of Onesimus."
  },
  "hebrews": {
    "en": "Jesus is the perfect high priest of the new covenant.",
    "ko": "예수님은 새 언약의 완전한 대제사장이십니다.",
    "es": "Jesus is the perfect high priest of the new covenant.",
    "fr": "Jesus is the perfect high priest of the new covenant.",
    "pt": "Jesus is the perfect high priest of the new covenant.",
    "it": "Jesus is the perfect high priest of the new covenant.",
    "de": "Jesus is the perfect high priest of the new covenant.",
    "pl": "Jesus is the perfect high priest of the new covenant.",
    "vi": "Jesus is the perfect high priest of the new covenant.",
    "tl": "Jesus is the perfect high priest of the new covenant."
  },
  "james": {
    "en": "Faith must show itself in works of mercy and self-control.",
    "ko": "믿음은 자비와 절제의 행동으로 드러나야 합니다.",
    "es": "Faith must show itself in works of mercy and self-control.",
    "fr": "Faith must show itself in works of mercy and self-control.",
    "pt": "Faith must show itself in works of mercy and self-control.",
    "it": "Faith must show itself in works of mercy and self-control.",
    "de": "Faith must show itself in works of mercy and self-control.",
    "pl": "Faith must show itself in works of mercy and self-control.",
    "vi": "Faith must show itself in works of mercy and self-control.",
    "tl": "Faith must show itself in works of mercy and self-control."
  },
  "1-peter": {
    "en": "Peter encourages suffering Christians to hope in Christ.",
    "ko": "베드로는 고난 중 희망을 격려합니다.",
    "es": "Peter encourages suffering Christians to hope in Christ.",
    "fr": "Peter encourages suffering Christians to hope in Christ.",
    "pt": "Peter encourages suffering Christians to hope in Christ.",
    "it": "Peter encourages suffering Christians to hope in Christ.",
    "de": "Peter encourages suffering Christians to hope in Christ.",
    "pl": "Peter encourages suffering Christians to hope in Christ.",
    "vi": "Peter encourages suffering Christians to hope in Christ.",
    "tl": "Peter encourages suffering Christians to hope in Christ."
  },
  "2-peter": {
    "en": "Peter warns against false teachers and affirms Christ's return.",
    "ko": "베드로는 거짓 교사를 경고하고 주님 오심을 확신합니다.",
    "es": "Peter warns against false teachers and affirms Christ's return.",
    "fr": "Peter warns against false teachers and affirms Christ's return.",
    "pt": "Peter warns against false teachers and affirms Christ's return.",
    "it": "Peter warns against false teachers and affirms Christ's return.",
    "de": "Peter warns against false teachers and affirms Christ's return.",
    "pl": "Peter warns against false teachers and affirms Christ's return.",
    "vi": "Peter warns against false teachers and affirms Christ's return.",
    "tl": "Peter warns against false teachers and affirms Christ's return."
  },
  "1-john": {
    "en": "John teaches that God is love and calls believers to fellowship.",
    "ko": "요한은 하느님이 사랑이심을 가르칩니다.",
    "es": "John teaches that God is love and calls believers to fellowship.",
    "fr": "John teaches that God is love and calls believers to fellowship.",
    "pt": "John teaches that God is love and calls believers to fellowship.",
    "it": "John teaches that God is love and calls believers to fellowship.",
    "de": "John teaches that God is love and calls believers to fellowship.",
    "pl": "John teaches that God is love and calls believers to fellowship.",
    "vi": "John teaches that God is love and calls believers to fellowship.",
    "tl": "John teaches that God is love and calls believers to fellowship."
  },
  "2-john": {
    "en": "John urges truth and love in the Christian community.",
    "ko": "요한은 진리와 사랑을 권합니다.",
    "es": "John urges truth and love in the Christian community.",
    "fr": "John urges truth and love in the Christian community.",
    "pt": "John urges truth and love in the Christian community.",
    "it": "John urges truth and love in the Christian community.",
    "de": "John urges truth and love in the Christian community.",
    "pl": "John urges truth and love in the Christian community.",
    "vi": "John urges truth and love in the Christian community.",
    "tl": "John urges truth and love in the Christian community."
  },
  "3-john": {
    "en": "John praises hospitality and faithful leadership in the Church.",
    "ko": "요한은 환대와 충실한 지도를 칭찬합니다.",
    "es": "John praises hospitality and faithful leadership in the Church.",
    "fr": "John praises hospitality and faithful leadership in the Church.",
    "pt": "John praises hospitality and faithful leadership in the Church.",
    "it": "John praises hospitality and faithful leadership in the Church.",
    "de": "John praises hospitality and faithful leadership in the Church.",
    "pl": "John praises hospitality and faithful leadership in the Church.",
    "vi": "John praises hospitality and faithful leadership in the Church.",
    "tl": "John praises hospitality and faithful leadership in the Church."
  },
  "jude": {
    "en": "Jude exhorts believers to contend for the faith once delivered.",
    "ko": "유다는 전해진 신앙을 지키라고 권합니다.",
    "es": "Jude exhorts believers to contend for the faith once delivered.",
    "fr": "Jude exhorts believers to contend for the faith once delivered.",
    "pt": "Jude exhorts believers to contend for the faith once delivered.",
    "it": "Jude exhorts believers to contend for the faith once delivered.",
    "de": "Jude exhorts believers to contend for the faith once delivered.",
    "pl": "Jude exhorts believers to contend for the faith once delivered.",
    "vi": "Jude exhorts believers to contend for the faith once delivered.",
    "tl": "Jude exhorts believers to contend for the faith once delivered."
  },
  "apocalypse": {
    "en": "John sees Christ's victory and the wedding feast of the Lamb.",
    "ko": "요한은 그리스도의 승리와 어린 양의 혼례 잔치를 봅니다.",
    "es": "Juan contempla la victoria de Cristo y la boda del Cordero.",
    "fr": "Jean voit la victoire du Christ et les noces de l'Agneau.",
    "pt": "Juan contempla la victoria de Cristo y la boda del Cordero.",
    "it": "Giovanni vede la vittoria di Cristo e le nozze dell'Agnello.",
    "de": "Johannes sieht Christi Sieg und das Hochzeitsmahl des Lammes.",
    "pl": "Jan widzi zwycięstwo Chrystusa i ucztę Baranka.",
    "vi": "Gioan thấy chiến thắng của Chúa Kitô và lễ cưới Chiên Con.",
    "tl": "Nakita ni Juan ang tagumpay ni Kristo at ang piging ng Kordero."
  }
};

export function getBookSpecificBlurb(
  bookSlug: string,
  locale: PrayerLanguageCode,
): string | undefined {
  return BOOK_BLURBS[bookSlug]?.[locale];
}
