import type { PrayerLanguageCode } from "@/lib/prayers/prayer-languages";

export type BookNoteCategory =
  | "pentateuch"
  | "historical"
  | "wisdom"
  | "prophetic"
  | "deuterocanon"
  | "gospel"
  | "acts"
  | "pauline"
  | "catholic_epistle"
  | "apocalypse";

export const BOOK_NOTE_CATEGORY: Readonly<Record<string, BookNoteCategory>> = {
  genesis: "pentateuch",
  exodus: "pentateuch",
  leviticus: "pentateuch",
  numbers: "pentateuch",
  deuteronomy: "pentateuch",
  josue: "historical",
  judges: "historical",
  ruth: "historical",
  "1-kings-samuel": "historical",
  "2-kings-samuel": "historical",
  "3-kings": "historical",
  "4-kings": "historical",
  "1-paralipomenon": "historical",
  "2-paralipomenon": "historical",
  "1-esdras": "historical",
  "2-esdras-nehemias": "historical",
  esther: "historical",
  job: "wisdom",
  psalms: "wisdom",
  proverbs: "wisdom",
  ecclesiastes: "wisdom",
  "canticle-of-canticles": "wisdom",
  wisdom: "wisdom",
  ecclesiasticus: "wisdom",
  isaias: "prophetic",
  jeremias: "prophetic",
  lamentations: "prophetic",
  baruch: "prophetic",
  ezechiel: "prophetic",
  daniel: "prophetic",
  osee: "prophetic",
  joel: "prophetic",
  amos: "prophetic",
  abdias: "prophetic",
  jonas: "prophetic",
  micheas: "prophetic",
  nahum: "prophetic",
  habacuc: "prophetic",
  sophonias: "prophetic",
  aggeus: "prophetic",
  zacharias: "prophetic",
  malachias: "prophetic",
  tobias: "deuterocanon",
  judith: "deuterocanon",
  "1-machabees": "deuterocanon",
  "2-machabees": "deuterocanon",
  matthew: "gospel",
  mark: "gospel",
  luke: "gospel",
  john: "gospel",
  acts: "acts",
  romans: "pauline",
  "1-corinthians": "pauline",
  "2-corinthians": "pauline",
  galatians: "pauline",
  ephesians: "pauline",
  philippians: "pauline",
  colossians: "pauline",
  "1-thessalonians": "pauline",
  "2-thessalonians": "pauline",
  "1-timothy": "pauline",
  "2-timothy": "pauline",
  titus: "pauline",
  philemon: "pauline",
  hebrews: "catholic_epistle",
  james: "catholic_epistle",
  "1-peter": "catholic_epistle",
  "2-peter": "catholic_epistle",
  "1-john": "catholic_epistle",
  "2-john": "catholic_epistle",
  "3-john": "catholic_epistle",
  jude: "catholic_epistle",
  apocalypse: "apocalypse",
};

type CategoryBlurbs = Record<PrayerLanguageCode, string>;

export const CATEGORY_NOTE_BLURBS: Record<BookNoteCategory, CategoryBlurbs> = {
  pentateuch: {
    en: "The Pentateuch tells how God formed his people Israel and gave the Law.",
    es: "El Pentateuco relata cómo Dios formó a su pueblo Israel y dio la Ley.",
    fr: "Le Pentateuque raconte comment Dieu a formé son peuple Israël et donné la Loi.",
    ko: "모세 오경은 하나님께서 이스라엘 백성을 세우시고 율법을 주신 이야기입니다.",
    pt: "O Pentateuco conta como Deus formou o seu povo Israel e deu a Lei.",
    it: "Il Pentateuco racconta come Dio formò il suo popolo Israele e diede la Legge.",
    de: "Der Pentateuch erzählt, wie Gott sein Volk Israel bildete und das Gesetz gab.",
    pl: "Pięcioksiąg opowiada, jak Bóg ukształtował swój lud Izrael i dał Prawo.",
    vi: "Ngũ Kinh kể Chúa lập dân Israel và ban Luật.",
    tl: "Ang Pentateuch ay nagsasalaysay kung paano hinubog ng Diyos ang bayang Israel at ibinigay ang Kautusan.",
  },
  historical: {
    en: "Historical books recount Israel's story from the conquest through exile and return.",
    es: "Los libros históricos narran la historia de Israel desde la conquista hasta el exilio y el retorno.",
    fr: "Les livres historiques racontent l'histoire d'Israël de la conquête à l'exil et au retour.",
    ko: "역사서는 정복부터 유배와 귀환까지 이스라엘의 역사를 전합니다.",
    pt: "Os livros históricos narram a história de Israel da conquista ao exílio e ao retorno.",
    it: "I libri storici raccontano la storia di Israele dalla conquista all'esilio e al ritorno.",
    de: "Die Geschichtsbücher erzählen Israels Geschichte von der Eroberung bis zu Exil und Rückkehr.",
    pl: "Księgi historyczne opowiadają dzieje Izraela od podboju po wygnanie i powrót.",
    vi: "Sách lịch sử thuật lại câu chuyện Israel từ cuộc chinh phục đến lưu đày và trở về.",
    tl: "Ang mga aklat na pangkasaysayan ay nagsasalaysay ng kasaysayan ng Israel mula pananakop hanggang pagkabihag at pagbabalik.",
  },
  wisdom: {
    en: "Wisdom literature teaches prayer, virtue, and trust in God amid daily life.",
    es: "La literatura sapiencial enseña oración, virtud y confianza en Dios en la vida diaria.",
    fr: "Les livres sapientiaux enseignent la prière, la vertu et la confiance en Dieu au quotidien.",
    ko: "지혜서는 일상 속에서 기도와 덕, 하나님 신뢰를 가르칩니다.",
    pt: "A literatura sapiencial ensina oração, virtude e confiança em Deus na vida diária.",
    it: "I libri sapienziali insegnano preghiera, virtù e fiducia in Dio nella vita quotidiana.",
    de: "Weisheitsliteratur lehrt Gebet, Tugend und Gottvertrauen im Alltag.",
    pl: "Literatura mądrościowa uczy modlitwy, cnoty i zaufania Bogu w codzienności.",
    vi: "Sách khôn ngoan dạy cầu nguyện, đức hạnh và tin cậy Chúa trong đời sống.",
    tl: "Ang panitikang karunungan ay nagtuturo ng panalangin, kabutihan, at pagtitiwala sa Diyos sa araw-araw.",
  },
  prophetic: {
    en: "The prophets call Israel to covenant faithfulness and hope in God's promises.",
    es: "Los profetas llaman a Israel a la fidelidad a la alianza y a la esperanza en las promesas de Dios.",
    fr: "Les prophètes appellent Israël à la fidélité à l'alliance et à l'espérance des promesses de Dieu.",
    ko: "예언서는 언약 신실과 하나님 약속의 희망을 외칩니다.",
    pt: "Os profetas chamam Israel à fidelidade à aliança e à esperança nas promessas de Deus.",
    it: "I profeti chiamano Israele alla fedeltà all'alleanza e alla speranza nelle promesse di Dio.",
    de: "Die Propheten rufen Israel zur Bundestreue und Hoffnung auf Gottes Verheißungen.",
    pl: "Prorocy wzywają Izrael do wierności przymierzu i nadziei w obietnice Boga.",
    vi: "Các tiên tri mời gọi Israel trung tín với giao ước và hy vọng vào lời hứa của Chúa.",
    tl: "Tinatawag ng mga propeta ang Israel sa katapatan sa tipan at pag-asa sa mga pangako ng Diyos.",
  },
  deuterocanon: {
    en: "Deuterocanonical books are treasured in the Catholic Bible for faith and courage.",
    es: "Los libros deuterocanónicos son apreciados en la Biblia católica por la fe y el valor.",
    fr: "Les livres deutérocanoniques sont chéris dans la Bible catholique pour la foi et le courage.",
    ko: "준경전은 가톨릭 성경에서 믿음과 용기를 일깨워 주는 책들입니다.",
    pt: "Os livros deuterocanônicos são estimados na Bíblia católica pela fé e coragem.",
    it: "I libri deuterocanonici sono preziosi nella Bibbia cattolica per fede e coraggio.",
    de: "Die deuterokanonischen Bücher sind in der katholischen Bibel Schätze des Glaubens und Muts.",
    pl: "Księgi deuterokanoniczne są drogocenne w Biblii katolickiej dla wiary i odwagi.",
    vi: "Các sách huynh đệ được trân trọng trong Kinh Thánh Công giáo vì đức tin và can đảm.",
    tl: "Ang mga aklat na deuterocanonical ay pinahahalagahan sa Bibliang Katoliko dahil sa pananampalataya at tapang.",
  },
  gospel: {
    en: "The Gospels proclaim the life, death, and Resurrection of Jesus Christ.",
    es: "Los Evangelios proclaman la vida, muerte y Resurrección de Jesucristo.",
    fr: "Les Évangiles proclament la vie, la mort et la Résurrection de Jésus-Christ.",
    ko: "복음서는 예수 그리스도의 생애, 수난, 부활을 선포합니다.",
    pt: "Os Evangelhos proclamam a vida, morte e Ressurreição de Jesus Cristo.",
    it: "I Vangeli proclamano la vita, morte e Resurrezione di Gesù Cristo.",
    de: "Die Evangelien verkünden Leben, Tod und Auferstehung Jesu Christi.",
    pl: "Ewangelie głoszą życie, śmierć i Zmartwychwstanie Jezusa Chrystusa.",
    vi: "Tin Mừng loan báo đời sống, cái chết và Sự Phục sinh của Chúa Giêsu Kitô.",
    tl: "Ipinapahayag ng mga Ebanghelyo ang buhay, kamatayan, at Muling Pagkabuhay ni Jesucristo.",
  },
  acts: {
    en: "Acts tells how the Holy Spirit spread the Church from Jerusalem to the nations.",
    es: "Hechos relata cómo el Espíritu Santo extendió la Iglesia desde Jerusalén a las naciones.",
    fr: "Les Actes racontent comment l'Esprit Saint a étendu l'Église de Jérusalem aux nations.",
    ko: "사도행전은 성령께서 교회를 예루살렘에서 열바구에까지 퍼뜨리신 이야기입니다.",
    pt: "Atos conta como o Espírito Santo espalhou a Igreja de Jerusalém às nações.",
    it: "Atti racconta come lo Spirito Santo diffuse la Chiesa da Gerusalemme alle nazioni.",
    de: "Die Apostelgeschichte erzählt, wie der Heilige Geist die Kirche von Jerusalem zu den Völkern trug.",
    pl: "Dzieje Apostolskie opowiadają, jak Duch Święty rozlał Kościół z Jerozolimy na narody.",
    vi: "Công vụ thuật lại Thánh Thần mở rộng Hội Thánh từ Giêrusalem đến các dân.",
    tl: "Isinasalaysay ng Mga Gawa kung paano pinalawak ng Espiritu Santo ang Simbahan mula Jerusalem hanggang sa mga bansa.",
  },
  pauline: {
    en: "Paul's letters teach faith in Christ and life in the Church.",
    es: "Las cartas de Pablo enseñan la fe en Cristo y la vida en la Iglesia.",
    fr: "Les lettres de Paul enseignent la foi au Christ et la vie dans l'Église.",
    ko: "바오로 서간은 그리스도 안의 믿음과 교회 안의 삶을 가르칩니다.",
    pt: "As cartas de Paulo ensinam a fé em Cristo e a vida na Igreja.",
    it: "Le lettere di Paolo insegnano la fede in Cristo e la vita nella Chiesa.",
    de: "Die Briefe des Paulus lehren Glauben an Christus und Leben in der Kirche.",
    pl: "Listy Pawła uczą wiary w Chrystusa i życia w Kościele.",
    vi: "Thư của Phaolô dạy đức tin vào Chúa Kitô và sống trong Hội Thánh.",
    tl: "Itinuturo ng mga sulat ni Pablo ang pananampalataya kay Kristo at buhay sa Simbahan.",
  },
  catholic_epistle: {
    en: "Catholic epistles encourage holiness, love, and perseverance in Christ.",
    es: "Las cartas católicas animan a la santidad, el amor y la perseverancia en Cristo.",
    fr: "Les épîtres catholiques encouragent la sainteté, l'amour et la persévérance en Christ.",
    ko: "공동 서간은 그리스도 안에서 거룩함과 사랑, 인내를 격려합니다.",
    pt: "As cartas católicas encorajam santidade, amor e perseverança em Cristo.",
    it: "Le lettere cattoliche incoraggiano santità, amore e perseveranza in Cristo.",
    de: "Die katholischen Briefe ermutigen zu Heiligkeit, Liebe und Ausdauer in Christus.",
    pl: "Listy powszechne zachęcają do świętości, miłości i wytrwałości w Chrystusie.",
    vi: "Thư công giáo khuyến khích sống thánh, yêu thương và bền lòng trong Chúa Kitô.",
    tl: "Hinihikayat ng mga sulat na Katoliko ang kabanalan, pag-ibig, at pagtitiis kay Kristo.",
  },
  apocalypse: {
    en: "Revelation unveils Christ's victory and the hope of a new heaven and earth.",
    es: "El Apocalipsis revela la victoria de Cristo y la esperanza de un cielo y tierra nuevos.",
    fr: "L'Apocalypse dévoile la victoire du Christ et l'espérance d'un ciel et d'une terre nouveaux.",
    ko: "요한 묵시록은 그리스도의 승리와 새 하늘과 땅의 희망을 보여 줍니다.",
    pt: "O Apocalipse revela a vitória de Cristo e a esperança de um novo céu e terra.",
    it: "L'Apocalisse svela la vittoria di Cristo e la speranza di un nuovo cielo e terra.",
    de: "Die Offenbarung enthüllt Christi Sieg und die Hoffnung auf einen neuen Himmel und Erde.",
    pl: "Apokalipsa ukazuje zwycięstwo Chrystusa i nadzieję nowego nieba i ziemi.",
    vi: "Khải Huyền mạc bà chiến thắng của Chúa Kitô và hy vọng trời đất mới.",
    tl: "Inihahayag ng Apocalipsis ang tagumpay ni Kristo at ang pag-asa sa bagong langit at lupa.",
  },
};

export function chapterNoteSummary(
  locale: PrayerLanguageCode,
  bookName: string,
  chapter: number,
  totalChapters: number,
  blurb: string,
): string {
  const templates: Record<PrayerLanguageCode, (b: string, c: number, t: number, text: string) => string> = {
    en: (b, c, t, text) => `${b}, chapter ${c} of ${t}. ${text}`,
    es: (b, c, t, text) => `${b}, capítulo ${c} de ${t}. ${text}`,
    fr: (b, c, t, text) => `${b}, chapitre ${c} sur ${t}. ${text}`,
    ko: (b, c, t, text) => `${b} ${c}장(총 ${t}장). ${text}`,
    pt: (b, c, t, text) => `${b}, capítulo ${c} de ${t}. ${text}`,
    it: (b, c, t, text) => `${b}, capitolo ${c} di ${t}. ${text}`,
    de: (b, c, t, text) => `${b}, Kapitel ${c} von ${t}. ${text}`,
    pl: (b, c, t, text) => `${b}, rozdział ${c} z ${t}. ${text}`,
    vi: (b, c, t, text) => `${b}, chương ${c}/${t}. ${text}`,
    tl: (b, c, t, text) => `${b}, kabanata ${c} sa ${t}. ${text}`,
  };
  const template = templates[locale] ?? templates.en;
  return template(bookName, chapter, totalChapters, blurb);
}
